In [10]:
import sys
import os
import numpy as np

sys.path.append(os.path.abspath("../../mathematical_models"))
from mathematical_models.s_on_f import ScalarOnFunctionModel
from mathematical_models.f_on_f import FunctionOnFunctionModel
from mathematical_models.s_on_s import ScalarOnScalarModel

sys.path.append(os.path.abspath("../../optimizers"))
from optimizers.nbdo import NBDO

sys.path.append(os.path.abspath("../../utilities"))
from utilities.plotting.plot_fun import subplot_results

sys.path.append(os.path.abspath("../../basis"))
from basis.bspline import BSplineBasis
from basis.polynomial import PolynomialBasis
from basis.basis import plot_design
from basis.basis import Basis
from basis.fourier import FourierBasis

### Settings

In [11]:
N = 12
x_base = BSplineBasis(degree=0, total_knots_num=4) # C
bs_base = PolynomialBasis(degree=2) # H
bases_pairs = [(x_base, bs_base)]
s_on_f_model = ScalarOnFunctionModel(bases_pairs=bases_pairs)

In [12]:
optimizer_s_on_f = NBDO(model=s_on_f_model, latent_dim=2)

In [13]:
optimizer_s_on_f.compute_train_set(num_designs=500, runs=N)

In [14]:
optimizer_s_on_f.train_set

array([[-0.71917567,  0.59519549, -0.90071383, ..., -0.17681466,
        -0.7645676 , -0.54896674],
       [-0.47536967,  0.49895002,  0.03942093, ..., -0.52461752,
         0.58070776,  0.53693728],
       [-0.2553055 , -0.03065498,  0.8267682 , ...,  0.39983805,
        -0.06146488, -0.06202297],
       ...,
       [ 0.60968423,  0.84673001,  0.6348669 , ..., -0.54734347,
        -0.02883501, -0.45212689],
       [ 0.57272474,  0.63002685, -0.47339802, ...,  0.87627903,
        -0.87055157, -0.51004914],
       [ 0.46159505,  0.00432238,  0.20606608, ...,  0.22053687,
         0.62710504,  0.77270811]])

In [15]:
history = optimizer_s_on_f.fit(epochs=100)

Epoch 1/100
13/13 [==============================] - 1s 10ms/step - loss: 101389.3516 - val_loss: 14496.6621
Epoch 2/100
13/13 [==============================] - 0s 2ms/step - loss: 10999.4629 - val_loss: 8241.6660
Epoch 3/100
13/13 [==============================] - 0s 2ms/step - loss: 6619.3101 - val_loss: 5156.5649
Epoch 4/100
13/13 [==============================] - 0s 2ms/step - loss: 4244.4883 - val_loss: 3332.5391
Epoch 5/100
13/13 [==============================] - 0s 2ms/step - loss: 2795.4619 - val_loss: 2155.7205
Epoch 6/100
13/13 [==============================] - 0s 2ms/step - loss: 1844.0217 - val_loss: 1382.0808
Epoch 7/100
13/13 [==============================] - 0s 2ms/step - loss: 1202.0732 - val_loss: 886.5054
Epoch 8/100
13/13 [==============================] - 0s 2ms/step - loss: 768.7678 - val_loss: 554.4091
Epoch 9/100
13/13 [==============================] - 0s 2ms/step - loss: 483.2552 - val_loss: 354.6395
Epoch 10/100
13/13 [==============================] - 0

In [16]:
best_cr, best_des = optimizer_s_on_f.optimize()

Iteration No: 1 started. Evaluating function at random point.
1/1 [==============================] - 0s 87ms/step
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.1524
Function value obtained: 2.7783
Current minimum: 2.7783
Iteration No: 2 started. Evaluating function at random point.
1/1 [==============================] - 0s 21ms/step
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0406
Function value obtained: 2.7783
Current minimum: 2.7783
Iteration No: 3 started. Evaluating function at random point.
1/1 [==============================] - 0s 13ms/step
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0367
Function value obtained: 2.7784
Current minimum: 2.7783
Iteration No: 4 started. Evaluating function at random point.
1/1 [==============================] - 0s 14ms/step
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0463
Function value obtained: 2.7787
Current minimum: 2.7783
Iteration No: 5 star

In [17]:
print(np.round(best_des, 3))

[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1. -1. -1.]
 [-1. -1.  1.]
 [ 1.  1. -1.]
 [-1.  1.  1.]
 [-1.  1.  1.]
 [-1. -1.  1.]
 [-1.  1.  1.]
 [ 1.  1. -1.]
 [-1. -1.  1.]
 [-1. -1. -1.]]
