In [1]:
import sys
import os
import numpy as np

sys.path.append(os.path.abspath("../../mathematical_models"))
from mathematical_models.s_on_f import ScalarOnFunctionModel
from mathematical_models.f_on_f import FunctionOnFunctionModel
from mathematical_models.s_on_s import ScalarOnScalarModel

sys.path.append(os.path.abspath("../../optimizers"))
from optimizers.nbdo import NBDO

sys.path.append(os.path.abspath("../../utilities"))
from utilities.plotting.plot_fun import subplot_results

### Settings

In [2]:
N = 80 # runs
Kx = [[20]]
epochs = 100
s_on_s_model = ScalarOnScalarModel(Kx=Kx[0])

In [3]:
optimizer_s_on_s = NBDO(model=s_on_s_model, latent_dim=4)
optimizer_s_on_s.compute_train_set(num_designs=1_000, runs=N)
history = optimizer_s_on_s.fit(epochs=epochs)

Epoch 1/100


2024-08-20 18:48:14.456596: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


25/25 [==============================] - 1s 22ms/step - loss: 661588.6250 - val_loss: 1.8075
Epoch 2/100
25/25 [==============================] - 0s 17ms/step - loss: 0.9682 - val_loss: 0.4993
Epoch 3/100
25/25 [==============================] - 0s 14ms/step - loss: 0.3811 - val_loss: 0.3097
Epoch 4/100
25/25 [==============================] - 0s 14ms/step - loss: 0.2920 - val_loss: 0.2811
Epoch 5/100
25/25 [==============================] - 0s 13ms/step - loss: 0.2779 - val_loss: 0.2761
Epoch 6/100
25/25 [==============================] - 0s 13ms/step - loss: 0.2754 - val_loss: 0.2747
Epoch 7/100
25/25 [==============================] - 0s 14ms/step - loss: 0.2743 - val_loss: 0.2739
Epoch 8/100
25/25 [==============================] - 0s 15ms/step - loss: 0.2739 - val_loss: 0.2738
Epoch 9/100
25/25 [==============================] - 0s 15ms/step - loss: 0.2738 - val_loss: 0.2738
Epoch 10/100
25/25 [==============================] - 0s 16ms/step - loss: 0.2738 - val_loss: 0.2738
Epoch 

In [4]:
best_cr, best_des = optimizer_s_on_s.optimize()

Iteration No: 1 started. Evaluating function at random point.
1/1 [==============================] - 0s 65ms/step
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0913
Function value obtained: 0.2799
Current minimum: 0.2799
Iteration No: 2 started. Evaluating function at random point.
1/1 [==============================] - 0s 9ms/step
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0217
Function value obtained: 0.2770
Current minimum: 0.2770
Iteration No: 3 started. Evaluating function at random point.
1/1 [==============================] - 0s 9ms/step
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0204
Function value obtained: 0.2741
Current minimum: 0.2741
Iteration No: 4 started. Evaluating function at random point.
1/1 [==============================] - 0s 9ms/step
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0214
Function value obtained: 0.2797
Current minimum: 0.2741
Iteration No: 5 started

In [5]:
print(np.round(best_des, 0))

[[ 1.  1. -1. ... -1. -1. -1.]
 [ 1. -1.  1. ... -1.  1.  1.]
 [ 1.  1.  1. ... -1. -1. -1.]
 ...
 [-1. -1. -1. ...  1. -1. -1.]
 [ 1.  1. -1. ...  1. -1. -1.]
 [ 1.  1. -1. ...  1. -1.  1.]]


In [6]:
best_cr

0.27374523179748994

In [10]:
print(np.round(best_des.T @ best_des))

[[ 80.   0.  -8.   2.  -4.   4.   4.   6.   0.  -0.  -4.  -0.  -4.   0.
    2.  -6.  -0.   2.   2.   4.]
 [  0.  80.   4.  -6.  -0.   0.   4.  -2.   4.   0.   0.   4.  -8.  -0.
    2.  -2.   4.   2.   2.  -4.]
 [ -8.   4.  80.   2.  -0.  -4.   4.   2.  -0.   0.   0.  -4.  -4.  -8.
   -2.  -2.  -8.  -2.   2.  -0.]
 [  2.  -6.   2.  80.   6.   2.   2.  -0.   2.  -2.   2.  -2.   2. -10.
   -4.   0.   2.  -4.  -0.   6.]
 [ -4.  -0.  -0.   6.  80.  -4.   0.  -2.   0.  -0.   4.   0.   8.  -0.
    2.  -6.  -4.  -2.   2.   4.]
 [  4.   0.  -4.   2.  -4.  80.   0.   2.   0.  -4.  -4.  -0.  -4.   4.
   -6.  -2.  -0.  -2.   2.  -4.]
 [  4.   4.   4.   2.   0.   0.  80.   2.   4.  -4.   4.   8.   0.   0.
   -2.  -2.  -0. -10.   2.  -0.]
 [  6.  -2.   2.  -0.  -2.   2.   2.  80.   6.  -6.  -2.  -6.  -2.  -2.
    4.   0.   6.  -0.  -4.   6.]
 [  0.   4.  -0.   2.   0.   0.   4.   6.  80.  -0.   4.   4.  -4.  -8.
    2.   2.  -0.  -2.   2.   0.]
 [ -0.   0.   0.  -2.  -0.  -4.  -4.  -6.  -0.  80.   8