In [1]:
import sys
import os
import numpy as np

sys.path.append(os.path.abspath("../../mathematical_models"))
from mathematical_models.s_on_f import ScalarOnFunctionModel
from mathematical_models.f_on_f import FunctionOnFunctionModel
from mathematical_models.s_on_s import ScalarOnScalarModel

sys.path.append(os.path.abspath("../../optimizers"))
from optimizers.nbdo import NBDO

sys.path.append(os.path.abspath("../../utilities"))
from utilities.plotting.plot_fun import subplot_results

### Settings

In [2]:
N = 4 # runs
Kx_family = 'step'
Kx = [[16]]
Kb = [[2]] # Polynomial
epochs = 100
s_on_f_model = ScalarOnFunctionModel(Kx=Kx[0], Kb= Kb[0], Kx_family=Kx_family)

In [3]:
optimizer_s_on_f = NBDO(model=s_on_f_model, latent_dim=2)
optimizer_s_on_f.compute_train_set(num_designs=500, runs=N)
history = optimizer_s_on_f.fit(epochs=epochs)

Epoch 1/100


2024-08-16 21:03:07.172779: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


13/13 [==============================] - 1s 10ms/step - loss: 163213.2656 - val_loss: 30747.5391
Epoch 2/100
13/13 [==============================] - 0s 2ms/step - loss: 24397.7969 - val_loss: 15241.2559
Epoch 3/100
13/13 [==============================] - 0s 2ms/step - loss: 12657.1777 - val_loss: 8181.5723
Epoch 4/100
13/13 [==============================] - 0s 2ms/step - loss: 6864.8198 - val_loss: 4491.3486
Epoch 5/100
13/13 [==============================] - 0s 3ms/step - loss: 3765.1812 - val_loss: 2520.0505
Epoch 6/100
13/13 [==============================] - 0s 3ms/step - loss: 2094.4014 - val_loss: 1430.7896
Epoch 7/100
13/13 [==============================] - 0s 3ms/step - loss: 1176.2303 - val_loss: 820.4089
Epoch 8/100
13/13 [==============================] - 0s 4ms/step - loss: 665.2120 - val_loss: 486.2744
Epoch 9/100
13/13 [==============================] - 0s 2ms/step - loss: 386.7034 - val_loss: 294.5852
Epoch 10/100
13/13 [==============================] - 0s 2ms/step

In [4]:
best_cr, best_des = optimizer_s_on_f.optimize()

Iteration No: 1 started. Evaluating function at random point.
1/1 [==============================] - 0s 60ms/step
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0801
Function value obtained: 8.4347
Current minimum: 8.4347
Iteration No: 2 started. Evaluating function at random point.
1/1 [==============================] - 0s 8ms/step
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0214
Function value obtained: 8.4289
Current minimum: 8.4289
Iteration No: 3 started. Evaluating function at random point.
1/1 [==============================] - 0s 8ms/step
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0254
Function value obtained: 9.0458
Current minimum: 8.4289
Iteration No: 4 started. Evaluating function at random point.
1/1 [==============================] - 0s 11ms/step
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0257
Function value obtained: 9.0458
Current minimum: 8.4289
Iteration No: 5 starte

In [5]:
print(np.round(best_des, 3))

[[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -1. -1. -1.]
 [ 1.  1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]
