In [2]:
import sys
import os
import numpy as np

sys.path.append(os.path.abspath("../../mathematical_models"))
from mathematical_models.f_on_f import FunctionOnFunctionModel

sys.path.append(os.path.abspath("../../optimizers"))
from optimizers.nbdo import NBDO

sys.path.append(os.path.abspath("../../utilities"))
from utilities.plotting.plot_fun import subplot_results

### Settings

In [4]:
N = 4 # runs
Kx_family = 'step'
Kx = [[6]]
Kb = [[4]] # Polynomial
Ky = 2
Sigma_decay = 0
epochs = 100
model = FunctionOnFunctionModel(Kx=Kx[0], Kb= Kb[0], Kx_family=Kx_family, Ky=Ky, Sigma_decay=Sigma_decay)

In [5]:
optimizer = NBDO(model=model, latent_dim=2)
optimizer.compute_train_set(num_designs=500, runs=N)
history = optimizer.fit(epochs=epochs)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 7 is different from 6)

In [6]:
print(np.round(model.J_cb, 3))

[[1.    0.    0.    0.    0.   ]
 [0.    0.167 0.014 0.002 0.   ]
 [0.    0.167 0.042 0.011 0.003]
 [0.    0.167 0.069 0.029 0.013]
 [0.    0.167 0.097 0.057 0.034]
 [0.    0.167 0.125 0.094 0.071]
 [0.    0.167 0.153 0.14  0.129]]
