In [1]:
import sys
import os
import numpy as np

sys.path.append(os.path.abspath("../../mathematical_models"))
from mathematical_models.s_on_f import ScalarOnFunctionModel
from mathematical_models.f_on_f import FunctionOnFunctionModel
from mathematical_models.s_on_s import ScalarOnScalarModel

sys.path.append(os.path.abspath("../../optimizers"))
from optimizers.nbdo import NBDO

sys.path.append(os.path.abspath("../../utilities"))
from utilities.plotting.plot_fun import subplot_results

### Settings

In [2]:
N = 4 # runs
Kx_family = 'step'
Kx = [[16]]
Kb = [[2]] # Polynomial
epochs = 100
s_on_f_model = ScalarOnFunctionModel(Kx=Kx[0], Kb= Kb[0], Kx_family=Kx_family)

In [3]:
optimizer_s_on_f = NBDO(model=s_on_f_model, latent_dim=2)
optimizer_s_on_f.compute_train_set(num_designs=500, runs=N)
history = optimizer_s_on_f.fit(epochs=epochs)

Epoch 1/100


2024-08-16 19:18:07.539685: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


13/13 [==============================] - 1s 9ms/step - loss: 232868.4219 - val_loss: 48864.1055
Epoch 2/100
13/13 [==============================] - 0s 2ms/step - loss: 36850.6133 - val_loss: 24197.8672
Epoch 3/100
13/13 [==============================] - 0s 2ms/step - loss: 18901.3809 - val_loss: 13504.9766
Epoch 4/100
13/13 [==============================] - 0s 2ms/step - loss: 10854.9434 - val_loss: 8035.6094
Epoch 5/100
13/13 [==============================] - 0s 2ms/step - loss: 6517.6895 - val_loss: 4911.7095
Epoch 6/100
13/13 [==============================] - 0s 2ms/step - loss: 4000.2927 - val_loss: 3041.3223
Epoch 7/100
13/13 [==============================] - 0s 2ms/step - loss: 2478.7747 - val_loss: 1897.5498
Epoch 8/100
13/13 [==============================] - 0s 2ms/step - loss: 1549.2761 - val_loss: 1194.0780
Epoch 9/100
13/13 [==============================] - 0s 2ms/step - loss: 967.2347 - val_loss: 738.9460
Epoch 10/100
13/13 [==============================] - 0s 2ms/

In [4]:
best_cr, best_des = optimizer_s_on_f.optimize()

Iteration No: 1 started. Evaluating function at random point.
1/1 [==============================] - 0s 40ms/step
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0552
Function value obtained: 8.4360
Current minimum: 8.4360
Iteration No: 2 started. Evaluating function at random point.
1/1 [==============================] - 0s 9ms/step
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0213
Function value obtained: 8.4364
Current minimum: 8.4360
Iteration No: 3 started. Evaluating function at random point.
1/1 [==============================] - 0s 9ms/step
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0210
Function value obtained: 8.4288
Current minimum: 8.4288
Iteration No: 4 started. Evaluating function at random point.
1/1 [==============================] - 0s 9ms/step
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0221
Function value obtained: 8.4290
Current minimum: 8.4288
Iteration No: 5 started

In [7]:
print(np.round(best_des, 3))

[[-1. -1. -1. -1. -1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1.]
 [ 1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]
