In [8]:
import sys
import os
import numpy as np

sys.path.append(os.path.abspath("../../mathematical_models"))
from mathematical_models.s_on_s import ScalarOnScalarModel

sys.path.append(os.path.abspath("../../optimizers"))
from optimizers.cordex_discrete import CordexDiscrete

sys.path.append(os.path.abspath("../../utilities"))
from utilities.plotting.plot_fun import subplot_results, subplot_b_spline_results

### Settings

In [16]:
N = 10 # runs
Kx = [[4]]
epochs = 100
refinement_epochs = 100
lvls = np.linspace(-1., 1., 10)
model = ScalarOnScalarModel(Kx=Kx[0])

In [17]:
optimizer = CordexDiscrete(model, runs=N, levels=lvls)
best_design, best_objective_value = optimizer.optimize(epochs=epochs, refinement_epochs=refinement_epochs)

100%|██████████| 100/100 [00:01<00:00, 57.84it/s]


In [11]:
print(f'Best design:\n {best_design}')

Best design:
 [[ 1.  1. -1.  1.]
 [ 1. -1.  1. -1.]
 [ 1. -1. -1. -1.]
 [ 1.  1.  1. -1.]
 [-1.  1. -1. -1.]
 [-1. -1.  1.  1.]
 [-1.  1.  1. -1.]
 [-1. -1. -1. -1.]
 [ 1. -1. -1.  1.]
 [-1.  1.  1.  1.]]
